version: '3.7'

services:

  mysql:
    image: mysql:8.0.29 
    restart: always
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=bercomat_training
      - MYSQL_DATABASE=music
      - TZ=America/Buenos_Aires
    volumes:
      - ./data_containers/mysql:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  db_client:
    image: phpmyadmin:5.2.0-apache
    restart: always
    container_name: db_client
    hostname: db_client
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - TZ=America/Buenos_Aires
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10" 
